---
title: "prem_analysis"
output: html_document
---

## Setups

### Loading packages and custom functions

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(tidyverse)
library(here)
library(metafor)
library(metaAidR)
library(orchaRd)
library(ape)
library(clubSandwich)
library(metaAidR)
library(patchwork)

# custom functions - here
# this is to get small sample size corrected lnRR
# also, the correlated samples - MS should put formulas of what we used and assumptions
# averaged 
lnRR_func <- function(Mc, Nc, Me, Ne, aCV2c, aCV2e, rho = 0.8){
  yi<-log( Me / Mc) + 
    0.5 * ((aCV2e / Ne) - (aCV2c / Nc))	
  
  vi <- (aCV2c / Nc)  + (aCV2e / Ne) + rho*(sqrt(aCV2c)*sqrt(aCV2e)/(Nc+Ne))
  
  data.frame(yi,vi)
}

```

### Importing data

```{r data}

fishdata_2 <- read_csv(here("data", "pilot_data_preprocessed.csv"))

fishdata_2

# creating SD for just biological
# not quite sure why if_else does not work but ifesle does (handling NA???)
fishdata_2 %>% mutate(SDc = ifelse(Sc_technical_biological == "biological", Sc, NA), 
                      SDe = ifelse(Se_technical_biological == "biological", Se, NA)) -> dat

#
tree <- read.tree(here("data", "plot_cooked_fish_MA.tre"))

# giving a tree branch lengths
tree <- compute.brlen(tree)

# making into a correlation matrix
cor_tree <- vcv(tree,corr = T)

#plot(tree)

# adding Phylogeny column
dat$Phylogeny <- str_replace(dat$Species_Scientific, " ", "_")

colnames(cor_tree) %in% dat$Phylogeny 

```

### Getting effect size

```{r}
# calculate the average CV^2 per study where available
# then average that again
dat %>% group_by(Study_ID) %>% summarise(CV2c = mean((SDc/Mc)^2, na.rm = T), CV2e = mean((SDe/Me)^2, na.rm = T)) %>% ungroup() %>% summarise(aCV2c = mean(CV2c, na.rm = T), aCV2e = mean(CV2e, na.rm = T)) -> aCV2

# getting effect size
effect <- lnRR_func(Mc = dat$Mc, Nc = dat$Nc, Me = dat$Me, Ne = dat$Ne, aCV2c = aCV2[[1]], aCV2e = aCV2[[2]], rho = 0.8)

# effective N

dat %>% mutate(N_tilde = (Nc*Ne)/(Nc + Ne)) -> dat

#  merging
dat <- cbind(dat, effect)

# getting ride of lnRR = NA
# data reduced to 520 to 502
#dat %>% filter(is.na(yi) == F) -> rdat # reduced data

# we need VCV to account for controlling for shared controls
VCV_lnRR <- make_VCV_matrix(dat, V = "vi", cluster = "Cohort_ID", obs = "Effect_ID", rho = 0.5)

```

### Some plotting

```{r}
# mean 
qplot(yi, data = dat, geom = "histogram")
qplot(yi, data = dat, geom = "density")
# variance
qplot(vi, data = dat, geom = "histogram")
qplot(vi, data = dat, geom = "density")

# log variance
qplot(vi, data = dat, geom = "histogram", log = "x")
qplot(vi, data = dat, geom = "density", log = "x")
```

### Meta-analysis (random-effects model - wrong)

```{r}

ma1 <- rma(yi, vi, 
          test = "knha", 
          data = dat)

summary(ma1)

funnel(ma1, yaxis = "seinv")

```

### Meta-analysis (mulit)

```{r, eval=FALSE}

ma2 <- rma.mv(yi, vi,
             random = list(~1|Study_ID, 
                           ~1|Cohort_ID,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
          test = "t", 
          data = dat)

# heterogeneity
#round(i2_ml(ma2)*100,1)
#funnel(ma2, yaxis = "seinv")

# reducing 

ma3 <- rma.mv(yi, vi,
             random = list(~1|Study_ID, 
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
          test = "t", 
          data = dat)

#summary(ma3)
#anova(ma2,ma3)

# adding phylo and VCV

ma4 <- rma.mv(yi, VCV_lnRR,
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)

#summary(ma4)

# saving all the models - they take a long time to run so we do not want to run everytime

obj <- list(ma2, ma3, ma4)

save(obj, file = here("Rdata", "mas.RData"))

```


```{r}
load(here("Rdata", "mas.RData"))

summary(ma2)
summary(ma3)
summary(ma4) # smallest AIC

```


### Meta-regression

#### Categorical moderator

```{r, eval=FALSE}

# Cooking_Category
mr1 <- rma.mv(yi, VCV_lnRR,
              mod = ~ Cooking_Category - 1,
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
#summary(mr1)

```
```{r}
# plot
orchard_plot(mr1, mod = "Cooking_Category", xlab = "lnRR (effect size)")
```


#### Continuous moderator

```{r , eval=FALSE}
# PFAS_carbon_chain
mr2 <- rma.mv(yi, VCV_lnRR,
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
# summary(mr2)
# r2_ml(mr2)
# Temperature_in_Celsius +
mr3 <- rma.mv(yi, VCV_lnRR,
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
# summary(mr3)
# r2_ml(mr3)
# Length_cooking_time_in_s
mr4 <- rma.mv(yi, VCV_lnRR,
              mod = ~  Length_cooking_time_in_s,
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
# summary(mr4)
# r2_ml(mr4)
#Volume_liquid_ml

mr5 <- rma.mv(yi, VCV_lnRR,
              mod = ~ scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
# summary(mr5)
# r2_ml(mr5)

#Weight_sample_g (should not really matter)

mr6 <- rma.mv(yi, VCV_lnRR,
              mod = ~ scale(Moisture_loss_in_percent),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
# summary(mr6)
# r2_ml(mr6)

# putting all together

mr_all <- rma.mv(yi, VCV_lnRR,
              mod = ~ - 1 + Cooking_Category +
                scale(Temperature_in_Celsius) +
                scale(Length_cooking_time_in_s) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
summary(mr_all)
r2_ml(mr_all)
#orchard_plot(mr_all, mod = "Cooking_Category", xlab = "lnRR (effect size)")

# cooking time 2 SD below
mr_all_short <- rma.mv(yi, VCV_lnRR,
              mod = ~ - 1 + Cooking_Category +
                scale(Temperature_in_Celsius) +
                I(scale(Length_cooking_time_in_s) + 2) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)

#summary(mr_all_short)
# cooking time 2 SD above

# consdiering missing values etc
mr_all_long <- rma.mv(yi, VCV_lnRR,
              mod = ~ - 1 + Cooking_Category +
                scale(Temperature_in_Celsius) +
                I(scale(Length_cooking_time_in_s) - 2) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
#summary(mr_all_long)

save(mr1, mr2, mr3, mr4, mr5, mr6, mr_all, mr_all_short, mr_all_long, file = here("Rdata", "mrs.RData"))

```

```{r}
load(here("Rdata", "mrs.RData"))

summary(mr1)
r2_ml(mr1)

summary(mr2)
r2_ml(mr2)

summary(mr3)
r2_ml(mr3)

summary(mr4)
r2_ml(mr4)

summary(mr5)
r2_ml(mr5)

summary(mr6)
r2_ml(mr6)

summary(mr_all)
r2_ml(mr_all)

summary(mr_all_short)
summary(mr_all_long)

```


#### Continous moderator (subset analysis)

```{r}
# splitting datasets by cooking method 

# just oil first

odat <- subset(dat, Cooking_Category == "oil-based")
VCV_lnRR2 <-  make_VCV_matrix(odat, V = "vi", cluster = "Cohort_ID", obs = "Effect_ID", rho = 0.5)

include <- row.names(cor_tree) %in% odat$Phylogeny

cor_tree2 <- cor_tree[include, include]

dim(odat) # 303 effect sizes

# just oil

mr_oil <- rma.mv(yi, VCV_lnRR2,
              mod = ~ 
                scale(Temperature_in_Celsius) +
                scale(Length_cooking_time_in_s) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree2),
             test = "t", 
             data = odat)
summary(mr_oil)

# for plotting 

mr_oil1 <- rma.mv(yi, VCV_lnRR2,
              mod = ~ 
                scale(Temperature_in_Celsius) +
                Length_cooking_time_in_s +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree2),
             test = "t", 
             data = odat)
summary(mr_oil1)

mr_oil3 <- rma.mv(yi, VCV_lnRR2,
              mod = ~ 
                Temperature_in_Celsius +
                Length_cooking_time_in_s +
                PFAS_carbon_chain +
                log(Volume_liquid_ml),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree2),
             test = "t", 
             data = odat)
summary(mr_oil3)


# just water

wdat <- subset(dat, Cooking_Category == "water-based")

VCV_lnRR3 <-  make_VCV_matrix(wdat, V = "vi", cluster = "Cohort_ID", obs = "Effect_ID", rho = 0.5)

include <- row.names(cor_tree) %in% wdat$Phylogeny

cor_tree3 <- cor_tree[include, include]

dim(wdat) # 140 effect sizes

mr_water <- rma.mv(yi, VCV_lnRR3,
              mod = ~ 
                #scale(Temperature_in_Celsius) + # this is redundant 
                scale(Length_cooking_time_in_s) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree3),
             test = "t", 
             data = wdat)
summary(mr_water)

# for plotting


mr_water1 <- rma.mv(yi, VCV_lnRR3,
              mod = ~ 
                #scale(Temperature_in_Celsius) + # this is redundant 
                Length_cooking_time_in_s +
                PFAS_carbon_chain +
                log(Volume_liquid_ml),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree3),
             test = "t", 
             data = wdat)


# just water

ndat <- subset(dat,  Cooking_Category == "No liquid")

VCV_lnRR4 <-  make_VCV_matrix(ndat, V = "vi", cluster = "Cohort_ID", obs = "Effect_ID", rho = 0.5)

include <- row.names(cor_tree) %in% ndat$Phylogeny

cor_tree4 <- cor_tree[include, include]

dim(ndat) # 69 effect sizes

# this is from just one study (not very useful but we can check length of cooking still)
mr_no <- rma.mv(yi, vi, # VCV_lnRR4 does not converge
              mod = ~ 
                #scale(Temperature_in_Celsius) + # not different from length of cooking
                scale(Length_cooking_time_in_s), # +
                #scale(PFAS_carbon_chain),
             random = list(#~1|Study_ID, # this is from one study
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree4),
             test = "t", 
             data = ndat)
summary(mr_no)

# for plotting

mr_no1 <- rma.mv(yi, vi, # VCV_lnRR4 does not converge
              mod = ~ 
                #scale(Temperature_in_Celsius) + # not different from length of cooking
                Length_cooking_time_in_s, # +
                #scale(PFAS_carbon_chain),
             random = list(#~1|Study_ID, # this is from one study
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree4),
             test = "t", 
             data = ndat)
summary(mr_no)


save(mr_oil, mr_water, mr_no, mr_oil1, mr_water1, mr_no1, file = here("Rdata", "mrs2.RData"))

```
```{r}
load(here("Rdata", "mrs.RData"))

summary(mr_oil)
r2_ml(mr_oil)

summary(mr_water)
r2_ml(mr_water)

summary(mr_no)
r2_ml(mr_no)

```

#### Conditional estimates

```{r}
# something strange is happening between different cooking types 
# some conditional intercept
# Length_cooking_time_in_s 
qplot(Length_cooking_time_in_s, data = odat, geom = "histogram")
#max(odat$Length_cooking_time_in_s, na.rm = T)
# Volume_liquid_ml
qplot(Volume_liquid_ml, data = odat, geom = "histogram")
qplot(Volume_liquid_ml, data = dat, geom = "histogram")
qplot(log(Volume_liquid_ml), data = odat, geom = "histogram")
qplot(log(Volume_liquid_ml), data = dat, geom = "histogram")
#max(odat$Volume_liquid_ml, na.rm = T)

odat$max_cook_time <- odat$Length_cooking_time_in_s - max(odat$Length_cooking_time_in_s, na.rm = T)
odat$max_lnvolume <- log(odat$Volume_liquid_ml) - max(odat$Volume_liquid_ml, na.rm = T)

# so a lot of oild and cookign a long time - get rid of pfas nearly completely (the model says)
mr_oil2 <- rma.mv(yi, VCV_lnRR2,
              mod = ~ 
               max_cook_time +
                scale(PFAS_carbon_chain) +
                max_lnvolume,
                         random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree2),
             test = "t", 
             data = odat)
summary(mr_oil2)

```
### Bubble plots

#### All data 
```{r}
#TODO fix the code (work on it)

pred_cooking_len <-predict.rma(mr4) 

# plotting
# probably should write a function

fig_cooking_len <-  dat %>% 
  filter(!is.na(Length_cooking_time_in_s))  %>% # getting ride of NA values
  mutate(ymin = pred_cooking_len$ci.lb, 
         ymax = pred_cooking_len$ci.ub,
         ymin2 = pred_cooking_len$cr.lb,
         ymax2 = pred_cooking_len$cr.ub,
         pred = pred_cooking_len$pred) %>% 
  ggplot(aes(x = Length_cooking_time_in_s, y = yi, size = (1/sqrt(vi)))) +
  geom_point(aes(fill = Cooking_Category), shape = 21) +
  geom_smooth(aes(y = ymin2), method =  "loess", se = FALSE, lty =  "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymax2), method =  "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymin), method =  "loess", se = FALSE,lty = "dotted", lwd = 0.25, colour ="#D55E00") +
  geom_smooth(aes(y = ymax), method =  "loess", se = FALSE, lty ="dotted", lwd = 0.25, colour ="#D55E00") + 
  geom_smooth(aes(y = pred), method =  "loess", se = FALSE, lty ="dashed", lwd = 0.5, colour ="black") +  
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "Cooking length (in sec)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

fig_cooking_len
#ggsave(plot = fig_cooking_len, filename = "fig_cooking_len.pdf", height = 2, width = 8)

#Volume_liquid_ml

#summary(mr5)
#r2_ml(mr5)
# plotting
pred_volume_liquid <-predict.rma(mr5) 

fig_volume_liq <-  dat %>% 
  filter(!is.na(Volume_liquid_ml))  %>% # getting ride of NA values
  mutate(ymin = pred_volume_liquid$ci.lb, 
         ymax = pred_volume_liquid$ci.ub,
         ymin2 = pred_volume_liquid$cr.lb,
         ymax2 = pred_volume_liquid$cr.ub,
         pred = pred_volume_liquid$pred) %>% 
  ggplot(aes(x = log(Volume_liquid_ml), y = yi, size = (1/sqrt(vi)))) +
  geom_point(aes(fill = Cooking_Category), shape = 21) +
  geom_smooth(aes(y = ymin2), method =  "loess", se = FALSE, lty =  "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymax2), method =  "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymin), method =  "loess", se = FALSE,lty = "dotted", lwd = 0.25, colour ="#D55E00") +
  geom_smooth(aes(y = ymax), method =  "loess", se = FALSE, lty ="dotted", lwd = 0.25, colour ="#D55E00") + 
  geom_smooth(aes(y = pred), method =  "loess", se = FALSE, lty ="dashed", lwd = 0.5, colour ="black") +  
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "ln(the volume of liquid) (in ml)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

fig_volume_liq

```
```{r}

# cooking length

p1 <- ggplot(odat, aes(x = Length_cooking_time_in_s, y = yi, size = (1/sqrt(vi)))) +
  geom_point(fill = "green4", shape = 21) +
  geom_abline(intercept = mr_oil1$beta[[1]], slope = mr_oil1$beta[[3]], lty =  "dotted") +
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "Cooking length (in sec)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

p1

# PFAS chain length

p2 <- ggplot(odat, aes(x = PFAS_carbon_chain, y = yi, size = (1/sqrt(vi)))) +
  geom_point(fill = "green4", shape = 21) +
  geom_abline(intercept = mr_oil1$beta[[1]], slope = mr_oil1$beta[[4]], lty =  "dotted") +
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "Cooking length (in sec)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

p2

# liquid volume

 +
                log(Volume_liquid_ml)

# May not be good below
# 
# cooking length

pred_cooking_len2 <-predict.rma(mr_oil) 

# plotting
# probably should write a function

fig_cooking_len2 <-  odat %>% filter(!is.na(Length_cooking_time_in_s) & !is.na(Temperature_in_Celsius)) %>%
  filter(!is.na(Length_cooking_time_in_s))  %>% # getting ride of NA values
  mutate(ymin = pred_cooking_len2$ci.lb, 
         ymax = pred_cooking_len2$ci.ub,
         ymin2 = pred_cooking_len2$pi.lb,
         ymax2 = pred_cooking_len2$pi.ub,
         pred = pred_cooking_len2$pred) %>% 
  ggplot(aes(x = Length_cooking_time_in_s, y = yi, size = (1/sqrt(vi)))) +
  geom_point(fill = "green", shape = 21) +
  geom_smooth(aes(y = ymin2), method =  "loess", se = FALSE, lty =  "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymax2), method =  "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymin), method =  "loess", se = FALSE,lty = "dotted", lwd = 0.25, colour ="#D55E00") +
  geom_smooth(aes(y = ymax), method =  "loess", se = FALSE, lty ="dotted", lwd = 0.25, colour ="#D55E00") + 
  geom_smooth(aes(y = pred), method =  "loess", se = FALSE, lty ="dashed", lwd = 0.5, colour ="black") +  
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "Cooking length (in sec)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

fig_cooking_len2

# liquid volume
pred_volume_liquid2 <-predict.rma(mr_oil) 

fig_volume_liq2 <-  odat %>% filter(!is.na(Length_cooking_time_in_s) & !is.na(Temperature_in_Celsius)) %>%
  mutate(ymin = pred_volume_liquid2$ci.lb, 
         ymax = pred_volume_liquid2$ci.ub,
         ymin2 = pred_volume_liquid2$cr.lb,
         ymax2 = pred_volume_liquid2$cr.ub,
         pred = pred_volume_liquid2$pred) %>% 
  ggplot(aes(x = log(Volume_liquid_ml), y = yi, size = (1/sqrt(vi)))) +
  geom_point(fill = "green", shape = 21) +
  geom_smooth(aes(y = ymin2), method =  "loess", se = FALSE, lty =  "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymax2), method =  "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#0072B2") +
  geom_smooth(aes(y = ymin), method =  "loess", se = FALSE,lty = "dotted", lwd = 0.25, colour ="#D55E00") +
  geom_smooth(aes(y = ymax), method =  "loess", se = FALSE, lty ="dotted", lwd = 0.25, colour ="#D55E00") + 
  geom_smooth(aes(y = pred), method =  "loess", se = FALSE, lty ="dashed", lwd = 0.5, colour ="black") +  
  #ylim(-1, 2) + xlim(0, 1.5) +
  labs(x = "ln(the volume of liquid) (in ml)", y = "lnRR", size = "Precison (1/SE)") +
  #guides(fill = "none", colour = "none") +
  # themses
  theme_bw() +
  theme(legend.position= c(1, 1), legend.justification = c(1, 1)) +
  theme(legend.direction="horizontal") +
  #theme(legend.background = element_rect(fill = "white", colour = "black")) +
  theme(legend.background = element_blank()) +
  theme(axis.text.y = element_text(size = 10, colour ="black", hjust = 0.5, angle = 90)) 

fig_volume_liq2

```


### Publication bias

```{r}

# funnel

funnel(mr_all, yaxis = "seinv")

# Egger regression
egger_all <- rma.mv(yi, VCV_lnRR,
              mod = ~ - 1 + Cooking_Category +
                I(sqrt(1/N_tilde)) + 
                scale(Publication_year) + 
                scale(Temperature_in_Celsius) +
                scale(Length_cooking_time_in_s) +
                scale(PFAS_carbon_chain) +
                scale(log(Volume_liquid_ml)),
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
summary(egger_all)

#funnel(egger_all, yaxis = "seinv")
# little evidence
egger_n <- rma.mv(yi, VCV_lnRR,
              mod = ~ I(sqrt(1/N_tilde)) ,  
             random = list(~1|Study_ID, 
                           ~1|Phylogeny,
                           ~1|Species_common,
                           ~1|PFAS_type,
                           ~1|Effect_ID),
             R= list(Phylogeny = cor_tree),
             test = "t", 
             data = dat)
summary(egger_n)

save(egger_all, egger_n, file = here("Rdata", "eggers.RData"))

```

